name: Generate Podcast Feeds
on: [push] # run when someone pushes to the main branch.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # run the action to checkout branch
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Run Feed Generator
        uses: jackfobel/podcast-generator@main  #username/repositoryWithAciton@branch
